name: Continuous integration pipeline

on:
  push:
    branches: [main]

jobs:
  lint: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3 
        with: node-version: "14"
      - run: npm ci 
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_LOG_LEVEL: info
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run build
